name: all_tests
on: push
jobs:
  all_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: setup
        run: make setup
      - name: test
        run: make test
      - name: linter
        run: make lint
  decrypt_security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.SNYK_TOKEN }}" --output $HOME/my_secret my_secret.gpg
      - run: |
          {
            echo 'SNYK_TOKEN<<SNYK'
            cat $HOME/my_secret
            echo SNYK
          } >> $GITHUB_ENV
      - run: echo $SNYK_TOKEN
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: 195cd8e0-b090-4487-afcf-0ee8397eded4
