name: all_tests
on: push
jobs:
  all_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: setup
        run: make setup
      - name: test
        run: make test
      - name: linter
        run: make lint
  decrypt_security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.SNYK_TOKEN }}" --output $HOME/my_secret my_secret.gpg
      - run: SNYK_TOKEN=$(cat $HOME/my_secret)
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
